name: Python CI Practice

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate venv and install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
