name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create venv
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          cd src
          python -m pytest addition.py
